## 期交所選擇權報價

In [1]:
import pandas as pd
import numpy as np
import requests

queryDate = '2023/01/04'#選取日期
commodity_id = 'TXO'#台指選代號
MarketCode = '0'#日盤0，夜盤1

#get table
url = 'https://www.taifex.com.tw/cht/3/optDailyMarketReport' #目標網址

#擷取資料設定
payload = {'queryDate':queryDate,
      'commodity_id':commodity_id,
      'MarketCode':MarketCode}

data = requests.post(url, data=payload) #擷取網站內容
df = pd.read_html(data.text)[2] #轉成DataFrame
display(df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,日期：2023/01/04 臺指選擇權 ( TXO ) 行情表 2023/01/04 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,臺指選擇權 ( TXO ) 行情表 2023/01/04 08:45~13:45 一般交...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,結算價,漲跌價,漲跌%,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量,最後最佳買價,最後最佳賣價,歷史最高價,歷史最低價
4,TXO,202301W1,12600,Call,-,-,-,-,-,-,-,0,0,0,0,1490,1740,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,TXO,202309,17200,Put,-,-,-,-,3640,-,-,0,0,0,0,-,-,-,-
736,TXO,202309,17400,Call,48.5,48.5,44.5,44.5,44.5,▼-2.5,▼-5.32%,16,2,18,227,35,52,62,38.5
737,TXO,202309,17400,Put,-,-,-,-,3830,-,-,0,0,0,0,-,-,-,-
738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,小計:,529595,593533,1123128,514735,NaN,NaN,NaN,NaN
739,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,*成交量與未沖銷契約量均含鉅額交易成交之契約,NaN,NaN

In [2]:
#sort table
df.columns = df.iloc[3] #重新命名欄位名稱
df = df.iloc[4:-1,:] #擷取需要row
df['開盤價'] = df['開盤價'].replace('-', np.nan) #去除不必要的資訊
df.dropna(inplace=True) #將空值nan去除
display(df)

<ipython-input-2-48f4aa286d86>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['開盤價'] = df['開盤價'].replace('-', np.nan) #去除不必要的資訊
/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

3,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,結算價,漲跌價,漲跌%,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量,最後最佳買價,最後最佳賣價,歷史最高價,歷史最低價
7,TXO,202301W1,12700,Put,0.2,0.2,0.2,0.2,-,0,0%,0,1,1,505,-,0.4,5,0.2
9,TXO,202301W1,12800,Put,0.2,0.2,0.2,0.2,-,0,0%,0,5,5,109,-,0.3,7,0.2
11,TXO,202301W1,12900,Put,0.2,0.3,0.2,0.3,-,▲+0.1,▲+50.00%,108,2,110,532,-,0.3,8.3,0.1
13,TXO,202301W1,13000,Put,0.2,0.2,0.2,0.2,-,0,0%,0,1,1,344,-,0.3,10,0.1
17,TXO,202301W1,13200,Put,0.1,0.1,0.1,0.1,-,▼-0.1,▼-50.00%,0,11,11,2456,-,0.3,16,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,TXO,202309,12000,Put,400,400,400,400,400,▼-3,▼-0.74%,0,8,8,43,203,-,476,398
698,TXO,202309,13600,Call,910,910,905,905,905,▼-15,▼-1.63%,0,5,5,1,15.5,-,945,905
703,TXO,202309,14000,Put,1100,1150,1100,1150,1140,0,0%,0,3,3,44,1050,-,1290,1070
716,TXO,202309,15400,Call,234,234,234,234,234,▼-58,▼-19.86%,0,1,1,21,15.5,278,277,210
736,TXO,202309,17400,Call,48.5,48.5,44.5,44.5,44.5,▼-2.5,▼-5.32%,16,2,18,227,35,52,62,38.5

In [3]:
#整理需要的資訊
df['日期'] = queryDate #日期設定
#欄位擷取
df = df[['日期', '契約', '到期月份(週別)', '履約價', '買賣權', '開盤價', '最高價', '最低價', '最後成交價',
    '*盤後交易時段成交量', '*一般交易時段成交量', '*合計成交量', '*未沖銷契約量']]
display(df)

3,日期,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量
7,2023/01/04,TXO,202301W1,12700,Put,0.2,0.2,0.2,0.2,0,1,1,505
9,2023/01/04,TXO,202301W1,12800,Put,0.2,0.2,0.2,0.2,0,5,5,109
11,2023/01/04,TXO,202301W1,12900,Put,0.2,0.3,0.2,0.3,108,2,110,532
13,2023/01/04,TXO,202301W1,13000,Put,0.2,0.2,0.2,0.2,0,1,1,344
17,2023/01/04,TXO,202301W1,13200,Put,0.1,0.1,0.1,0.1,0,11,11,2456
...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,2023/01/04,TXO,202309,12000,Put,400,400,400,400,0,8,8,43
698,2023/01/04,TXO,202309,13600,Call,910,910,905,905,0,5,5,1
703,2023/01/04,TXO,202309,14000,Put,1100,1150,1100,1150,0,3,3,44
716,2023/01/04,TXO,202309,15400,Call,234,234,234,234,0,1,1,21
736,2023/01/04,TXO,202309,17400,Call,48.5,48.5,44.5,44.5,16,2,18,227

## 證交所台指大盤報價

In [4]:
#目標網址
url = 'https://www.twse.com.tw/zh/indicesReport/MI_5MINS_HIST'

date = 20230114

#擷取資料設定
payload = {'date':date}

data = requests.post(url, data=payload) #擷取網站內容

import json
#用json編譯
data = json.loads(data.text)
#轉成DataFrame
df = pd.DataFrame(data['data'])
#columns重新命名
df.columns = data['fields']

df[['民國年', '月', '日']] = df['日期'].str.split('/', expand=True) #將日期拆分
df['西元年'] = df['民國年'].astype(int) + 1911 #民國年+1911=西元年
df['日期'] = df['西元年'].astype(str) +'/'+ df['月'] +'/'+ df['日'] #重新將日期調整成西元格式
df = df[['日期', '開盤指數', '最高指數', '最低指數', '收盤指數']]

#資料型態轉換
df['開盤指數'] = df['開盤指數'].str.replace(',','').astype(float)
df['最高指數'] = df['最高指數'].str.replace(',','').astype(float)
df['最低指數'] = df['最低指數'].str.replace(',','').astype(float)
df['收盤指數'] = df['收盤指數'].str.replace(',','').astype(float)

display(df)

            日期      開盤指數      最高指數      最低指數      收盤指數
0   2023/01/03  14108.16  14237.94  14001.97  14224.12
1   2023/01/04  14186.95  14257.45  14177.97  14199.13
2   2023/01/05  14285.12  14357.60  14270.93  14301.05
3   2023/01/06  14278.52  14384.92  14278.52  14373.34
4   2023/01/09  14504.47  14752.21  14504.47  14752.21
5   2023/01/10  14796.27  14816.13  14728.56  14802.96
6   2023/01/11  14822.86  14842.74  14734.44  14751.44
7   2023/01/12  14780.58  14813.31  14700.73  14731.64
8   2023/01/13  14923.05  14962.31  14822.15  14824.13
9   2023/01/16  14895.26  14960.92  14895.26  14927.01
10  2023/01/17  14922.34  14945.23  14884.78  14932.93

## 將選擇權及大盤的爬蟲打包成函示庫

In [5]:
def option_data(queryDate, commodity_id, MarketCode):
  # queryDate = '2023/01/04'#選取日期
  # commodity_id = 'TXO'#台指選代號
  # MarketCode = '0'#日盤0，夜盤1

  #get table
  url = 'https://www.taifex.com.tw/cht/3/optDailyMarketReport' #目標網址

  payload = {'queryDate':queryDate,
        'commodity_id':commodity_id,
        'MarketCode':MarketCode}

  data = requests.post(url, data=payload) #擷取網站內容
  df = pd.read_html(data.text)[2] #轉成DataFrame

  #sort table
  df.columns = df.iloc[3] #重新命名欄位名稱
  df = df.iloc[4:-1,:] #擷取需要row
  df['開盤價'] = df['開盤價'].replace('-', np.nan) #去除不必要的資訊
  df.dropna(inplace=True) #將空值nan去除


  #整理需要的資訊
  df['日期'] = queryDate
  df = df[['日期', '契約', '到期月份(週別)', '履約價', '買賣權', '開盤價', '最高價', '最低價', '最後成交價',
      '*盤後交易時段成交量', '*一般交易時段成交量', '*合計成交量', '*未沖銷契約量']]

  return df

def TWSE_data(date):
  url = 'https://www.twse.com.tw/zh/indicesReport/MI_5MINS_HIST'

  # date = 20230104

  payload = {'date':date}

  data = requests.post(url, data=payload) #擷取網站內容

  data = json.loads(data.text)

  df = pd.DataFrame(data['data'])
  df.columns = data['fields']

  df[['民國年', '月', '日']] = df['日期'].str.split('/', expand=True) #將日期拆分
  df['西元年'] = df['民國年'].astype(int) + 1911 #民國年+1911=西元年
  df['日期'] = df['西元年'].astype(str) +'/'+ df['月'] +'/'+ df['日'] #重新將日期調整成西元格式

  df = df[['日期', '開盤指數', '最高指數', '最低指數', '收盤指數']]

  df['開盤指數'] = df['開盤指數'].str.replace(',','').astype(float)
  df['最高指數'] = df['最高指數'].str.replace(',','').astype(float)
  df['最低指數'] = df['最低指數'].str.replace(',','').astype(float)
  df['收盤指數'] = df['收盤指數'].str.replace(',','').astype(float)
  return df

import pandas as pd
import numpy as np
import requests
import json

option = option_data('2023/01/04', 'TXO', '0')
display(option)

TWSE = TWSE_data('20230104')
display(TWSE)

3,日期,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量
7,2023/01/04,TXO,202301W1,12700,Put,0.2,0.2,0.2,0.2,0,1,1,505
9,2023/01/04,TXO,202301W1,12800,Put,0.2,0.2,0.2,0.2,0,5,5,109
11,2023/01/04,TXO,202301W1,12900,Put,0.2,0.3,0.2,0.3,108,2,110,532
13,2023/01/04,TXO,202301W1,13000,Put,0.2,0.2,0.2,0.2,0,1,1,344
17,2023/01/04,TXO,202301W1,13200,Put,0.1,0.1,0.1,0.1,0,11,11,2456
...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,2023/01/04,TXO,202309,12000,Put,400,400,400,400,0,8,8,43
698,2023/01/04,TXO,202309,13600,Call,910,910,905,905,0,5,5,1
703,2023/01/04,TXO,202309,14000,Put,1100,1150,1100,1150,0,3,3,44
716,2023/01/04,TXO,202309,15400,Call,234,234,234,234,0,1,1,21
736,2023/01/04,TXO,202309,17400,Call,48.5,48.5,44.5,44.5,16,2,18,227

            日期      開盤指數      最高指數      最低指數      收盤指數
0   2023/01/03  14108.16  14237.94  14001.97  14224.12
1   2023/01/04  14186.95  14257.45  14177.97  14199.13
2   2023/01/05  14285.12  14357.60  14270.93  14301.05
3   2023/01/06  14278.52  14384.92  14278.52  14373.34
4   2023/01/09  14504.47  14752.21  14504.47  14752.21
5   2023/01/10  14796.27  14816.13  14728.56  14802.96
6   2023/01/11  14822.86  14842.74  14734.44  14751.44
7   2023/01/12  14780.58  14813.31  14700.73  14731.64
8   2023/01/13  14923.05  14962.31  14822.15  14824.13
9   2023/01/16  14895.26  14960.92  14895.26  14927.01
10  2023/01/17  14922.34  14945.23  14884.78  14932.93

In [6]:
#將大盤報價合併到選擇權資料
data = pd.merge(option, TWSE, on='日期', how='left')

#可以找到價平附近的資料
data['收盤差距'] = abs(data['履約價'].astype(float) - data['收盤指數'])

data

,日期,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量,開盤指數,最高指數,最低指數,收盤指數,收盤差距
0,2023/01/04,TXO,202301W1,12700,Put,0.2,0.2,0.2,0.2,0,1,1,505,14186.95,14257.45,14177.97,14199.13,1499.13
1,2023/01/04,TXO,202301W1,12800,Put,0.2,0.2,0.2,0.2,0,5,5,109,14186.95,14257.45,14177.97,14199.13,1399.13
2,2023/01/04,TXO,202301W1,12900,Put,0.2,0.3,0.2,0.3,108,2,110,532,14186.95,14257.45,14177.97,14199.13,1299.13
3,2023/01/04,TXO,202301W1,13000,Put,0.2,0.2,0.2,0.2,0,1,1,344,14186.95,14257.45,14177.97,14199.13,1199.13
4,2023/01/04,TXO,202301W1,13200,Put,0.1,0.1,0.1,0.1,0,11,11,2456,14186.95,14257.45,14177.97,14199.13,999.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,2023/01/04,TXO,202309,12000,Put,400,400,400,400,0,8,8,43,14186.95,14257.45,14177.97,14199.13,2199.13
318,2023/01/04,TXO,202309,13600,Call,910,910,905,905,0,5,5,1,14186.95,14257.45,14177.97,14199.13,599.13
319,2023/01/04,TXO,202309,14000,Put,1100,1150,1100,1150,0,3,3,44,14186.95,14257.45,14177.97,14199.13,199.13
320,2023/01/04,TXO,202309,15400,Call,234,234,234,234,0,1,1,21,14186.95,14257.45,14177.97,14199.13,1200.87
321,2023/01/04,TXO,202309,17400,Call,48.5,48.5,44.5,44.5,16,2,18,227,14186.95,14257.45,14177.97,14199.13,3200.87

In [7]:
data.loc[data['收盤差距']<200]#找價平附近的報價

,日期,契約,到期月份(週別),履約價,買賣權,開盤價,最高價,最低價,最後成交價,*盤後交易時段成交量,*一般交易時段成交量,*合計成交量,*未沖銷契約量,開盤指數,最高指數,最低指數,收盤指數,收盤差距
21,2023/01/04,TXO,202301W1,14000,Call,222,277,202,223,1147,2366,3513,1286,14186.95,14257.45,14177.97,14199.13,199.13
22,2023/01/04,TXO,202301W1,14000,Put,1.3,1.5,0.1,0.1,10054,9649,19703,10279,14186.95,14257.45,14177.97,14199.13,199.13
23,2023/01/04,TXO,202301W1,14050,Call,175,220,150,172,1730,2269,3999,1342,14186.95,14257.45,14177.97,14199.13,149.13
24,2023/01/04,TXO,202301W1,14050,Put,2.7,2.7,0.1,0.2,13165,9551,22716,7721,14186.95,14257.45,14177.97,14199.13,149.13
25,2023/01/04,TXO,202301W1,14100,Call,125,176,100,123,8198,11531,19729,1618,14186.95,14257.45,14177.97,14199.13,99.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,2023/01/04,TXO,202303,14000,Put,379,393,379,380,10,30,40,719,14186.95,14257.45,14177.97,14199.13,199.13
274,2023/01/04,TXO,202303,14200,Put,480,480,480,480,1,8,9,66,14186.95,14257.45,14177.97,14199.13,0.87
306,2023/01/04,TXO,202306,14000,Call,760,770,755,755,0,6,6,65,14186.95,14257.45,14177.97,14199.13,199.13
307,2023/01/04,TXO,202306,14200,Put,805,805,800,805,2,8,10,34,14186.95,14257.45,14177.97,14199.13,0.87
319,2023/01/04,TXO,202309,14000,Put,1100,1150,1100,1150,0,3,3,44,14186.95,14257.45,14177.97,14199.13,199.13